# 推荐系统训练集表
DROP TABLE IF EXISTS 'RECOMMENDER_TRAIN';
CREATE TABLE 'RECOMMENDER_TRAIN' (
  'ID' int(11) NOT NULL AUTO_INCREMENT,
  'USER_ID' int(11) NOT NULL,
  'ITEM_ID' int(11) NOT NULL,
  'RATING'  int(11) DEFAULT '0',
  PRIMARY KEY ('id')
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

# --推荐系统ITEMCF算法结果表
DROP TABLE IF EXISTS 'RECOMMENDER_ITEMCF_RESULT';
CREATE TABLE 'RECOMMENDER_RESULT' (
  'ID' int(11) NOT NULL AUTO_INCREMENT,
  'ITEM_ID' int(11) NOT NULL,
  'RESULT' varchar(5000) NOT NULL,
  'RESULT_DATE' date,
  PRIMARY KEY ('id')
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;